./shaderc/glslc.exe ./shaders/quad.vert -o ./spv/vert.spv --target-env=opengl -std=450core -I "./" -I "./shaders"
./shaderc/glslc.exe ./shaders/quad.frag -o ./spv/frag.spv --target-env=opengl -std=450core -I "./" -I "./shaders"
./shaderc/glslc.exe ./shaders/texturedQuad.frag -o ./spv/texturedQuadFrag.spv --target-env=opengl -std=450core -I "./" -I "./shaders"
./shaderc/glslc.exe ./shaders/fbmnoise.frag -o ./spv/fbmnoisefrag.spv --target-env=opengl -std=450core -I "./" -I "./shaders"
./shaderc/glslc.exe ./shaders/perlinnoise.frag -o ./spv/perlinnoisefrag.spv --target-env=opengl -std=450core -I "./" -I "./shaders"
./shaderc/glslc.exe ./shaders/worleynoise.frag -o ./spv/worleynoisefrag.spv --target-env=opengl -std=450core -I "./" -I "./shaders"